### ISSUE TITLE
panic on creating torrent

### ISSUE THREAD

**Issue by IgorShadurin** [xssnick/tonutils-storage#4] opened 2023-06-14 08:00 UTC
During running `create /Users/test/Downloads/GUI.Mac.M1.Tonutils.Proxy.dmg bbb` command I received error:

```
▀  Scanning files... (0s)panic: runtime error: slice bounds out of range [52:51]

goroutine 1 [running]:
github.com/xssnick/tonutils-storage/storage.CreateTorrent.func1({0x1400020a587, 0x33}, {0x100ef8db0?, 0x14000074a90?}, {0x0?, 0x0?})
	/Users/xssnick/dev/ton/tonutils-storage/storage/create.go:62 +0x4dc
path/filepath.walk({0x1400020a587, 0x33}, {0x100ef8db0, 0x14000074a90}, 0x140001e6ec0)
	/usr/local/go/src/path/filepath/path.go:433 +0xd0
path/filepath.Walk({0x1400020a587, 0x33}, 0x140001e6ec0)
	/usr/local/go/src/path/filepath/path.go:520 +0x6c
github.com/xssnick/tonutils-storage/storage.CreateTorrent({0x1400020a587, 0x33}, {0x1400020a5bb, 0x3}, {0x100ef9798, 0x1400023ecc0}, {0x100ef9460, 0x14000226840})
	/Users/xssnick/dev/ton/tonutils-storage/storage/create.go:53 +0x270
main.create({0x1400020a587?, 0x3e?}, {0x1400020a5bb?, 0x1?})
	/Users/xssnick/dev/ton/tonutils-storage/cli/main.go:245 +0x4c
main.main()
	/Users/xssnick/dev/ton/tonutils-storage/cli/main.go:192 +0x12e0
```

**Comment by xssnick** [comment] 2023-06-15 07:26
v0.2.0 Released with support of creation from files, could you please try again?

**Comment by IgorShadurin** [comment] 2023-06-15 10:04
Now separate files are added without errors. Information about the file from the local machine is visible on the VPS. But the file is not downloading. Directories are loaded normally.

In the "Completed" row, the value for files is false, for the directory - true.

**Comment by xssnick** [comment] 2023-06-16 06:58
Released v0.2.1, Included fix for this too, check please

**Comment by IgorShadurin** [comment] 2023-06-16 08:53
If I create a torrent from a file like this `create ./GUI.Mac.M1.Tonutils.Proxy.dmg aaa` or like this `create ton-torrent-mac-apple-silicon.dmg zzz111` it causes problems on the downloader side (using the official client).
`FATAL ERROR: Invalid torrent header: Invalid torrent header: Invalid dir_name: Name can't start with '/'`.

**Comment by xssnick** [comment] 2023-06-17 17:36
> If I create a torrent from a file like this `create ./GUI.Mac.M1.Tonutils.Proxy.dmg aaa` or like this `create ton-torrent-mac-apple-silicon.dmg zzz111` it causes problems on the downloader side (using the official client). `FATAL ERROR: Invalid torrent header: Invalid torrent header: Invalid dir_name: Name can't start with '/'`.

Fixed in v0.2.2

**Comment by IgorShadurin** [comment] 2023-06-17 21:10
The server is unable to download a single file with the new version. However, the downloading of directories proceeds without issue. Official client can get the name of the file, but the download process for the file simply has not started. The file was added using the command `create ton-torrent-mac-apple-silicon.dmg macsil`.

<img width="599" alt="Screenshot 2023-06-18 at 00 07 32" src="https://github.com/xssnick/tonutils-storage/assets/1595061/d5f6cfb6-98ca-4b58-bdf3-79b0169b4a2a">

**Comment by xssnick** [comment] 2023-06-18 07:24
> The server is unable to download a single file with the new version. However, the downloading of directories proceeds without issue. Official client can get the name of the file, but the download process for the file simply has not started. The file was added using the command `create ton-torrent-mac-apple-silicon.dmg macsil`.
> 
> <img alt="Screenshot 2023-06-18 at 00 07 32" width="599" src="https://user-images.githubusercontent.com/1595061/246631537-d5f6cfb6-98ca-4b58-bdf3-79b0169b4a2a.png">

I changed behavior in v0.2.3, it will work between tonutils-storage nodes. But not sure about storage-daemon, I think it may not work with empty directory names, so single file torrents may be incompatible by design, I will reach them to raise this issue.

For now you can use single file torrents with tonutils-storage

**Comment by xssnick** [comment] 2023-06-18 17:24
Tested v0.2.3 with storage-daemon, works fine for me too.

**Closed** 2023-06-20 05:00 UTC
